name: Ruby

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Load Ruby version
      run: echo "##[set-output name=RUBYV;]$(cat .tool-versions | sed 's/ruby //g')"
      id: rnv
    - name: Set up Ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: "${{ steps.rnv.outputs.RUBYV }}"
    - name: Build and test with Rake
      run: |
        apt install libsqlite3-dev
        gem install bundler
        bundle install --jobs 4 --retry 3
        bundle exec rake
